# Generated by Django 3.1.6 on 2021-03-31 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bumon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SAKUSEISHA', models.CharField(default='', max_length=70)),
                ('SAKUSEIYMD', models.DateField()),
                ('KOUSINSHA', models.CharField(default='', max_length=70)),
                ('KOUSINYMD', models.DateField()),
                ('DEPARTMENT_CODE', models.CharField(default='', max_length=70, unique=True)),
                ('DEPARTMENT_NAME', models.CharField(default='', max_length=70)),
            ],
            options={
                'db_table': 'MST_BUMON',
            },
        ),
        migrations.CreateModel(
            name='kihonjyouhou',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SAKUSEISHA', models.CharField(default='', max_length=70)),
                ('SAKUSEIYMD', models.DateField()),
                ('KOUSINSHA', models.CharField(default='', max_length=70)),
                ('KOUSINYMD', models.DateField()),
                ('EMPLOYEEID', models.CharField(default='', max_length=70, unique=True)),
                ('NAME', models.CharField(default='', max_length=70)),
                ('SEX', models.CharField(default='', max_length=70)),
                ('BIRTHDAY', models.DateField()),
                ('JOBGRADE', models.CharField(default='', max_length=70)),
                ('STATUS', models.CharField(default='', max_length=70)),
                ('ROLE_ID', models.CharField(default='', max_length=70)),
                ('CAPTURE', models.CharField(default='', max_length=70)),
                ('DEPARTMENT_CODE', models.CharField(default='', max_length=70)),
                ('ROOM_NO', models.CharField(default='', max_length=70)),
            ],
            options={
                'db_table': 'MST_KIHONJYOUHOU',
            },
        ),
        migrations.CreateModel(
            name='permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EMPLOYEEID', models.CharField(default='', max_length=70, unique=True)),
                ('PASSWORD', models.CharField(default='', max_length=70)),
                ('MODIFIED_YMD', models.DateField()),
                ('EXPIRED_DAYS', models.IntegerField(default=30, unique=True)),
                ('ROLE_ID', models.CharField(default='', max_length=70)),
                ('ROLE_NAME', models.CharField(default='', max_length=70)),
            ],
            options={
                'db_table': 'MST_PERMISSION',
            },
        ),
        migrations.CreateModel(
            name='records',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('No', models.IntegerField(default=1, unique=True)),
                ('SAKUSEISHA', models.CharField(default='', max_length=70)),
                ('SAKUSEIYMD', models.DateField()),
                ('KOUSINSHA', models.CharField(default='', max_length=70)),
                ('KOUSINYMD', models.DateField()),
                ('EMPLOYEEID', models.CharField(default='', max_length=70)),
                ('DAKOKU_TIME', models.DateField()),
                ('KUBUN', models.CharField(default='', max_length=70)),
            ],
            options={
                'db_table': 'TBL_SYUTAIKIN_RECORD',
            },
        ),
        migrations.CreateModel(
            name='room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SAKUSEISHA', models.CharField(default='', max_length=70)),
                ('SAKUSEIYMD', models.DateField()),
                ('KOUSINSHA', models.CharField(default='', max_length=70)),
                ('KOUSINYMD', models.DateField()),
                ('ROOM_NO', models.CharField(default='', max_length=70, unique=True)),
                ('ROOM_NAME', models.CharField(default='', max_length=70)),
            ],
            options={
                'db_table': 'MST_ROOM',
            },
        ),
    ]
